version: '3.8'

services:
  backend:
    build:
      context: ./Dolores-Backend
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    environment:
      - SECRET_KEY=
      - MONGO_ROOT_USERNAME=
      - MONGO_ROOT_PASSWORD=
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./Dolores-Frontend/dist:/app:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:rw
  db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
